### ISSUE TITLE
Should support (or document as unsupported) commands beginning w/ a `|`.

### ISSUE THREAD

**Issue by drmuey** [pandax381/ngx_http_pipelog_module#6]
In issue #5 initially the logs were not being written because the command started w/ a `|` which is what is needed for Apache.

Took some code diving to determine it needed the `|` removed.

Before: `pipelog "|/usr/local/cpanel/bin/splitlogs …`
After: `pipelog "/usr/local/cpanel/bin/splitlogs …`

**Comment by pandax381** [comment]
Thank you for your feedback.

Apache uses `|` to determine that the output destination is a command (via a pipe), not a file, but the pipelog module does not use `|` because the output destination is always a command.

On the other hand, this specification is likely to be misleading for Apache users ... I will document it according to your advice.

Thanks!

**Comment by drmuey** [comment]
you’re welcome, thank you :)

**Comment by pandax381** [comment]
Fixed.
